INSERT INTO
    `sz-00009-ws.datasetGCP.faturas_fio_raw` (
        `GUID`,
        `nome_cliente`,
        `subgrupo_tarifario`,
        `mes_referencia`,
        `endereco_cliente`,
        `base_calc_cofins`,
        `COFINS`,
        `base_calc_pis`,
        `PIS`,
        `base_calc_pis_cofins`,
        `pis_cofins`,
        `base_calc_icms`,
        `ICMS`,
        `numero_instalacao`,
        `numero_cliente`,
        `numero_fatura`,
        `data_emissao`,
        `codigo_barras`,
        `total_fatura`,
        `data_vencimento`,
        `cnpj_cliente`,
        `cnpj_fornecedor`,
        `nome_fornecedor`,
        `mensagem_aviso`,
        `reservado_fisco`,
        `tipo_cliente`,
        `tipo_fatura`,
        `obs_gerais`,
        `URI`,
        `tipo_layout`
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);